### ISSUE TITLE
can you remove when you put /clearchat this messages?

### ISSUE THREAD

**Issue by SoyPro** [paetti/ChatToolsPro#1]
[ClearChat]
[ClearChat]
[ClearChat]
[ClearChat]
[ClearChat]
[ClearChat]
and can you add config.yml to config messages?

**Comment by paetti** [comment]
Good idea, ima try :) and which command with config? Well I could make like /pfs (Prefix Say) That it broadcasts like [MagicGamers] message and you can config the tag or what you mean?

**Comment by SoyPro** [comment]
yes i mean that i can config the [ClearChat] message, and maybe in the future you can add /lockchat and /unlock chat, this is for if there is to much lag or spam, and can you add chat was cleared by [player] or chat was locked by [player]

**Comment by paetti** [comment]
Adding the functions.
